tap "buo/cask-upgrade"
tap "caskroom/cask"
tap "caskroom/drivers"
tap "caskroom/eid"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/versions"
tap "vitorgalvao/tiny-scripts"
cask "java"
brew "aalib"
brew "docbook"
brew "asciidoc", args: ["with-docbook-xsl"]
brew "freetype"
brew "fontconfig"
brew "gettext"
brew "libffi"
brew "pixman"
brew "cairo"
brew "perl"
brew "git"
brew "openssl"
brew "gdbm"
brew "atk"
brew "autoconf"
brew "autoenv"
brew "automake"
brew "babl"
brew "bash"
brew "bash-completion"
brew "bazel"
brew "boost"
brew "ccache", args: ["HEAD"]
brew "clang-format"
brew "cmake"
brew "coreutils"
brew "cscope"
brew "ctags"
brew "curl"
brew "dbus", restart_service: true
brew "docbook-xsl"
brew "gmp"
brew "isl"
brew "mpfr"
brew "libmpc"
brew "gcc"
brew "gd"
brew "gdb"
brew "gdk-pixbuf"
brew "git-hooks"
brew "lua"
brew "gnuplot"
brew "go"
brew "gradle"
brew "gsettings-desktop-schemas"
brew "icu4c"
brew "hicolor-icon-theme"
brew "gtk+"
brew "xz"
brew "python3"
brew "gtk+3"
brew "py2cairo"
brew "pygobject"
brew "pygtk"
brew "gtk-mac-integration"
brew "intltool"
brew "ipython"
brew "kotlin"
brew "libcroco"
brew "libevent"
brew "librsvg"
brew "libtool"
brew "libwmf"
brew "libyaml"
brew "llvm"
brew "mas"
brew "mobile-shell"
brew "ninja"
brew "numpy"
brew "pyenv"
brew "pyenv-virtualenv"
brew "pyenv-virtualenvwrapper"
brew "pypy3"
brew "qt"
brew "reattach-to-user-namespace"
brew "ruby"
brew "shellcheck"
brew "swig"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "wget"
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "1password"
cask "alfred"
cask "android-studio"
cask "android-studio-canary"
cask "bartender"
cask "beardedspice"
cask "bettertouchtool"
cask "cheatsheet"
cask "cuda"
cask "dragand"
cask "eclipse-java"
cask "eve"
cask "evernote"
cask "firefox"
cask "flume"
cask "github-desktop"
cask "goofy"
cask "google-chrome"
cask "google-photos-backup-and-sync"
cask "grammarly"
cask "iina"
cask "istat-menus"
cask "kap"
cask "karabiner-elements"
cask "keepingyouawake"
cask "keka"
cask "kindle"
cask "musixmatch"
cask "onedrive"
cask "qt-creator"
cask "ship"
cask "skype-for-business"
cask "slack"
cask "spotifree"
cask "spotify"
cask "synergy"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "wireshark"
mas "Affinity Photo", id: 824183456
mas "AutoMute", id: 1118136179
mas "Commander One PRO", id: 1035237815
mas "Disk Care", id: 913724705
mas "Filters for Photos", id: 1083965373
mas "GarageBand", id: 682658836
mas "GIF Brewery 3", id: 1081413713
mas "HwpMac2014VIEWER", id: 416746898
mas "iMovie", id: 408981434
mas "KakaoTalk", id: 869223134
mas "Keynote", id: 409183694
mas "Leaf", id: 576338668
mas "LOCK for Netflix", id: 1120947587
mas "Lunar", id: 966148899
mas "Microsoft OneNote", id: 784801555
mas "MonthlyCal", id: 935250717
mas "MP4 Converter", id: 665534836
mas "Music Converter", id: 468990728
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PDF Expert", id: 1055273043
mas "Polarr Photo Editor", id: 1058273036
mas "Shazam", id: 897118787
mas "The Unarchiver", id: 425424353
mas "Things3", id: 904280696
mas "WeBlog", id: 1242308270
mas "Xcode", id: 497799835
